(setq opc1 1)
(setq opc2 2)
(setq opc3 3)

(defun hola (x)
	(if (eq x opc1)
		(princ "Opcion 1!")
		(if (eq x opc2)
			(princ "Opcion 2!")
			(if (eq x opc3)
				(princ "Opcion 3!")
					(princ "Esa Opcion No Existe!"))))
	(terpri))
(hola 4)
